name: deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          yarn

      - name: Build
        run: yarn build

      - name: Deploy S3
        uses: techmmunity/action-deploy-static-webapp-aws@1.0.0
        with:
          build_path: "./dist"
          bucket_name: ${{ secrets.S3_BUCKET }}
          distribution_invalidation_path: "/*"
        env:
          DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
          AWS_REGION: ${{ secrets.S3_BUCKET_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.STATIC_FRONTEND_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.STATIC_FRONTEND_AWS_SECRET_ACCESS_KEY }}
